<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>RestExceptions</PackageId>
    <Title>RestExceptions</Title>
    <Version>10.0.0</Version>

    <Authors>Stratis-Dermanoutsos</Authors>

    <Copyright>Copyright © Stratis Dermanoutsos 2026</Copyright>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>

    <PackageProjectUrl>https://github.com/stratisd-labs/rest-exceptions-dotnet</PackageProjectUrl>
    <RepositoryUrl>https://github.com/stratisd-labs/rest-exceptions-dotnet</RepositoryUrl>

    <Description>Extensible Web API middleware that maps all exceptions to standardized RFC7807-compliant HTTP responses.</Description>
    <PackageTags>open-source http oss rest errors csharp dotnet exceptions problem-details rfc7807</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>* Upgraded to .NET 10 and C# 14.
    </PackageReleaseNotes>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <!--  Required to have the AddProblemDetails extension  -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../LICENSE" Pack="true" PackagePath="/"/>
    <None Include="../../README.md" Pack="true" PackagePath="/"/>
  </ItemGroup>
</Project>
